### ISSUE TITLE
InvalidChainId when calling debug_traceTransaction on mainnet-fork

### ISSUE THREAD

**Issue by antazoey** [NomicFoundation/edr#533] opened 2024-06-26 18:28 UTC
### Version of Hardhat

2.22.5

### What happened?

I am running a simple Ethereum mainnet-fork hardhat node but when I call `debug_traceTransaction()` with transaction hash '0x0537316f37627655b7fe5e50e23f71cd835b377d1cde4226443c94723d036e32', I get the following response error:

```
{'jsonrpc': '2.0', 'id': 15, 'error': {'code': -32603, 'message': 'Invalid transaction: InvalidChainId', 'data': {'message': 'Invalid transaction: InvalidChainId', 'data': None}}}
```

### Minimal reproduction steps

Start node.
Use your favorite REST tool to call debug_traceTransaction with the only arg as '0xf5fa49d357c705373c7432f15154d7d64d4f4e0105f23d18e31ed6353b28fb41'
Observe response.

### Search terms

debug_traceTransaction, debug_tt, fork

**Comment by fvictorio** [comment] 2024-07-01 14:54
Confirmed. I also tried other transactions in the same block, and they didn't work either. Also: this seems to work in `hardhat@2.20.1`, so definitely a regression.

**Comment by fvictorio** [comment] 2024-07-26 15:02
Hey @antazoey, sorry that we haven't fixed this yet; hopefully we'll do it next week.

For the time being, there is this workaround: you can configure the Hardhat network chain id to match the remote one. In the case of mainnet:

```js
networks: {
  hardhat: {
    chainId: 1
```

Notice that this is slightly dangerous if you are using a real account and not the test ones, because any transaction you sign could be replayed (assuming someone can access it). But this is unlikely to be an issue in practice.

**Comment by antazoey** [comment] 2024-07-26 15:08
> Hey @antazoey, sorry that we haven't fixed this yet; hopefully we'll do it next week.

No worries! It is only affecting tooling (noticed in our acceptance testing). Thanks for the update.

**Comment by agostbiro** [comment] 2024-07-31 07:45
Hey @antazoey thanks for reporting this! We have merged a fix for this issue and it's due to be released next week. Let us know if you need it sooner please!

**Closed** 2024-08-05 14:35 UTC
