### ISSUE TITLE
Create GitHub workflow for running runtime benchmarks

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#54] opened 2023-01-13 15:24 UTC
**Definition of Done**
Create a triggerable GitHub CI workflow, which should be runnable on a dedicated (Linux) runner that:
- runs Rethnet's Criterion benchmarks
- publishes the results to a dedicated GitHub repository
- generates a static GH page
- only runs automatically for members of the Nomic organisation
- can be manually triggered for people that are not members of the Nomic organisation

See this [example](https://github.com/NomicFoundation/self-hosted-runner-experiments/blob/main/.github/workflows/benchmark.yml#L9) for how to run on our custom runner.

See this [GitHub action](https://github.com/benchmark-action/github-action-benchmark/blob/master/examples/criterion-rs/README.md) for running Criterion benchmarks and automatically creating a static GH page with the results.

This is what a historic graph will look like:

![Image](https://user-images.githubusercontent.com/6917585/236953897-ff7f7d50-69de-4af6-881e-67545d61766d.png)
source: https://benchmark-action.github.io/github-action-benchmark/dev/bench/

**Comment by agostbiro** [comment] 2024-03-27 14:36
Closing as duplicate of https://github.com/NomicFoundation/edr/issues/313

**Closed by agostbiro** 2024-03-27 14:36 UTC
Labels: type: feat
