### ISSUE TITLE
estimateGas returns 21001 on native eth transfer

### ISSUE THREAD

**Issue by prudanoff** [NomicFoundation/edr#542] opened 2024-06-29 09:21 UTC
### Version of Hardhat

2.22.5

### What happened?

I'm trying to transfer all ETH from one wallet to another. When creating a transaction, I manually specified gasLimit: 21000 and received the error `"Sender doesn't have enough funds to send tx"`
During the investigation, I found out that the hardhat node is waiting for me to send it 21001 gas, while the transaction will spend only 21000 and 1 gas will remain on the account.

### Minimal reproduction steps

`balance.ts`
```js
const { ethers } = require("hardhat");
async function main() {
    const [deployer] = await ethers.getSigners();
    let estimateGas = await ethers.provider.estimateGas({
        to: deployer.address,
        value: 100
    })
    console.log(`estimateGas: ${estimateGas}`);
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
```
Starting brand new node:
`npx hardhat node`
Executing script:
`npx hardhat run .\scripts\balance.ts --network localhost`
Result:
`estimateGas: 21001`

**Comment by alcuadrado** [comment] 2024-07-03 19:41
I'm transferring this to EDR, as i believe it's our `eth_estimateGas` implementation.

**Comment by workingabalone** [comment] 2024-07-04 08:27
Hello @prudanoff  A support ticket has been opened for you. Kindly Talk to  Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by fvictorio** [comment] 2024-07-04 13:06
Hi @prudanoff, I think you are saying some things that are not necessarily related.

1. It is true that Hardhat returns 21001 as the gas estimation of an ETH transfer, because [we add 1 to the initial estimation](https://github.com/NomicFoundation/edr/blob/df23ef43bfc35cc40e4c665ddee575ebcc0f9eb7/crates/edr_provider/src/data.rs#L746-L748). That has been the behavior for a while, but to be honest I don't remember the reason for this (@alcuadrado do you?)
2. The fact that a value of 21001 is returned doesn't mean that the transaction will be rejected if you use a gas limit that's less than that. The result of an `eth_estimateGas` call is basically saying "if you use this value as the gas limit, then I think the transaction will not run out of gas, and the actual gas used won't be way less than this".
3. You are also saying that you get a `"Sender doesn't have enough funds to send tx"` error when sending eth with a gas limit of 21_000. But that is about the balance of the sender, not about the gas limit. If this were about the gas limit, then the transaction would be executed anyway and you'd get an out of gas error. What that error is saying is that the balance of the account is less than `gasLimit * gasPrice`. (Just in case, I did send a tx to an EOA using 21_000 as the gas limit and it worked fine.)

I'm tentatively closing this because I think it's just a confusion. But I'll re-open it if you can clarify or provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of something that's not working as expected.

**Closed by fvictorio** 2024-07-04 13:06 UTC

**Comment by fvictorio** [comment] 2024-07-04 19:50
Ah that makes sense, thanks for explaining!
